### ISSUE TITLE
How to build?

### ISSUE THREAD

**Issue by MMLead** [lvsti/CEF.swift#19] opened 2017-07-31 23:48 UTC
I've tried "The easy way" with carthage and "The oldschool way" with setup.sh and I'm unable to build this. Mac OS 10.12.6 Xcode 8.3.3

I'm excited to use this repo, but I'm a little new to Xcode, thank you! :dizzy:

Carthage:
```
$ carthage update
*** Fetching CEF.swift
*** Checking out CEF.swift at "394a73be54e67fe3f940ba161dd21c501dced756"
*** xcodebuild output can be found in /var/folders/5k/4vq3cwgd0_95wnn91bn_15n80000gn/T/carthage-xcodebuild.WJrjb3.log
*** Building scheme "CEF.swift" in CEF.swift.xcodeproj
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -project /Users/andys/CEF.swift/Carthage/Checkouts/CEF.swift/CEF.swift.xcodeproj -scheme CEF.swift -configuration Release -derivedDataPath /Users/andys/Library/Caches/org.carthage.CarthageKit/DerivedData/CEF.swift/394a73be54e67fe3f940ba161dd21c501dced756 ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build (launched in /Users/andys/CEF.swift/Carthage/Checkouts/CEF.swift)

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/5k/4vq3cwgd0_95wnn91bn_15n80000gn/T/carthage-xcodebuild.WJrjb3.log
```

scripts/setup.sh
```
$ sudo scripts/setup.sh
Password:
+ '[' '' = true ']'
++ git rev-parse --abbrev-ref HEAD
+ BRANCH=cef_3071
+ '[' cef '!=' cef ']'
+ CEF_BRANCH=3071
++ which 7z
+ '[' -z /usr/local/bin/7z ']'
++ which jq
+ '[' -z /usr/local/bin/jq ']'
++ which cmake
+ '[' -z /usr/local/bin/cmake ']'
+ echo 'Fetching binary distribution...'
Fetching binary distribution...
++ curl http://opensource.spotify.com/cefbuilds/index.html
++ scripts/cefbuilds_spotify.py -x --platforms=macosx64 --branches=3071 -
++ jq '."macosx64"."3071"'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0Traceback (most recent call last):
  File "scripts/cefbuilds_spotify.py", line 9, in <module>
    from lxml import html
ImportError: No module named lxml
  4 1623k    4 82536    0     0  1587k      0  0:00:01 --:--:--  0:00:01 1612k
curl: (23) Failed writing body (0 != 1448)
+ CEFBUILD_DESCRIPTOR=
++ echo
++ jq .dists.standard
++ tr -d '"'
+ CEFBUILD_URL=
++ echo
++ jq .delta
++ tr -d '"'
+ CEFBUILD_VERSION=3071.
++ mktemp -d /tmp/cefbuild.XXX
+ CEFBUILD_TEMP=/tmp/cefbuild.Rhv
+ CEFBUILD_TEMP_PATH=/tmp/cefbuild.Rhv/3071..tar.bz2
+ curl '' -k -o /tmp/cefbuild.Rhv/3071..tar.bz2
curl: (3) <url> malformed
+ echo 'Extracting package...'
Extracting package...
+ mkdir -p External
+ tar xzf /tmp/cefbuild.Rhv/3071..tar.bz2 -C External
tar: Error opening archive: Failed to open '/tmp/cefbuild.Rhv/3071..tar.bz2'
++ tar -tzf /tmp/cefbuild.Rhv/3071..tar.bz2
++ head -1
++ tr -d /
tar: Error opening archive: Failed to open '/tmp/cefbuild.Rhv/3071..tar.bz2'
+ CEFBUILD_DIR_NAME=
+ rm -rf /tmp/cefbuild.Rhv
+ '[' -e External/cef_binary ']'
+ ln -s '' External/cef_binary
ln: External/cef_binary: Invalid argument
+ pushd .
~/CEF.swift ~/CEF.swift
+ cd External/cef_binary
scripts/setup.sh: line 64: cd: External/cef_binary: No such file or directory
+ cmake -G Xcode
CMake Error: The source directory "/Users/andys/CEF.swift" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
+ set -o pipefail
+ xcodebuild clean build -project cef.xcodeproj -target 'cefsimple Helper' -arch x86_64 -configuration Debug
+ xcpretty -c
scripts/setup.sh: line 66: xcpretty: command not found
xcodebuild: error: 'cef.xcodeproj' does not exist.
+ set -o pipefail
+ xcodebuild clean build -project cef.xcodeproj -target 'cefsimple Helper' -arch x86_64 -configuration Release
+ xcpretty -c
scripts/setup.sh: line 67: xcpretty: command not found
xcodebuild: error: 'cef.xcodeproj' does not exist.
+ popd
~/CEF.swift
```

**Comment by MMLead** [comment] 2017-08-01 00:27
Here is the carthage log. 
[carthage-xcodebuild.WJrjb3.txt](https://github.com/lvsti/CEF.swift/files/1189182/carthage-xcodebuild.WJrjb3.txt)

**Comment by lvsti** [comment] 2017-08-01 21:08
Hi,
the issue is probably this:

```
  File "scripts/cefbuilds_spotify.py", line 9, in <module>
    from lxml import html
ImportError: No module named lxml
```

please make sure you have lxml installed in your python environment

**Comment by MMLead** [comment] 2017-08-01 21:42
Thanks! Xcode dommand line tools, a fresh install of Python, and lxml resolved the issue, and I was able to build with `carthage update`.

* Xcode Command Line Tools:
`$ xcode-select --install`

* [Python](https://www.python.org/)

* lxml:
`sudo pip install lxml`


The `sudo scripts/setup.sh` still needs something called xcpretty? Should all this stuff be added to README.md?

**Comment by lvsti** [comment] 2017-10-04 19:45
README has been updated. Can I close this?

**Comment by powernerd** [comment] 2017-10-04 19:54
Yes, thanks for changing the README.

**Closed** 2017-10-13 18:24 UTC
